version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
    networks:
      - mynetwork

  mongodb:
    image: mongo:4
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mynetwork

  api:
    build: ./api
    container_name: api_backend
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - ./api/node_modules:/app/node_modules
      - ./api/database.sqlite:/app/database.sqlite
    env_file:
      - .env
    networks:
      - mynetwork

  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    env_file:
      - .env
    stdin_open: true
    tty: true
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
